baseURL = "https://ukki722.github.io/HugoTest/"
languageCode = "ja"
title = "My New Hugo Site"
hasCJKLanguage = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[Params]
subtitle = "Welcome Hugo World!"
author = "ウッキー"
introduce = "Hello world. 長い文章もなんのその。HugoとGithubを使って色々しているところです"

twitter ="vicvic4106"
github ="ukki722"

